### DISCUSSION TITLE
On compliance vs readability: Generating text colors with CSS • Lea Verou

### DISCUSSION THREAD

**Discussion by giscus** [LeaVerou/blog#94] [Blog Comments]
# 
		On compliance vs readability: Generating text colors with CSS • Lea Verou

https://lea.verou.me/blog/2024/contrast-color/

**Comment by proimage** [comment]
Really looking forward to this capability! I'd say the simple version you helped push through definitely works for well over 90% of the cases I've run into. 🥳

Personally, I'd love to see a final syntax along these lines:
```css
background-color: [color];
color: contrast-color(
        [color],
        var(--contrast-color--crossover),
        var(--contrast-color--light),
        var(--contrast-color--dark)
);
```
- `color` would be the color we're wanting to contrast with. This would be the only required param. I don't mind if it's also a CSS var, presumably defaulting to either white or `null` (OR... `currentBgColor`??? * hint hint *).

The rest of these are specified as CSS vars, to allow easy overriding at whichever level an author chooses.
- `--contrast-color--crossover` (default 0.5) would allow authors to customize when the algorithm chooses black vs white. Personally, I find white text to be more readable up until about the 0.6 contrast mark, so I'd probably set that globally on the sites I build.
- `--contrast-color--light` & `--contrast-color--dark` (defaults of `#fff` and `#000`, respectively) would allow authors to customize which exact colors get selected. They would be used by the contrast-calculation algorithm, and they (or the CSS variable?) would be the actual color that gets output in the end.

**Reply by LeaVerou** [reply]
Hey there! You may find this proposal interesting: https://github.com/w3c/csswg-drafts/issues/11534

**Reply by proimage** [reply]
Yay! I definitely think the light and dark color params should be a set order rather than letting the algo decide which is which.

Where would be a good place to propose user control of the contrast crossover point?

**Comment by dominikschreiber** [comment]
So hoping for the day `contrast-color()` becomes baseline available 🤞.

There is a way to apply this mechanism to more colors than just black and white, but it's cumbersome and works in Firefox only with the experimental `layout.css.style-queries.enabled` flag (see bug [1795622](https://bugzil.la/1795622)):

The idea is to not use the result of `oklch(from var(--color) var(--l) 0 h)` directly, but to put that into another custom property, and use a container style query against that property to figure out the actual value you want to apply. For that, you have to define this "intermediate" property using `@property` and set the hue always to `0` – otherwise the style query will most likely not match. But if you're willing to go this extra mile, you can switch between manually chosen colors today (almost, 👀 Firefox). Example:

```css
@property --blackOrWhite {
  syntax: "<color>";
  inherits: true;
  initial-value: red;
}

body {
  --background: #fff;
  --light: #300;
  --dark: #fcc;

  --l: clamp(0, (l / var(--l-threshold, 0.623) - 1) * -infinity, 1);
  --blackOrWhite: oklch(from var(--background) var(--l) 0 0);

  background-color: var(--background, #fff);
}

label {
  color: var(--color, var(--blackOrWhite));

  @container style(--blackOrWhite: oklch(0 0 0)) {
    --color: var(--light);
  }

  @container style(--blackOrWhite: oklch(1 0 0)) {
    --color: var(--dark);
  }
}
```

Small playground codepen: https://codepen.io/dominikschreiber-sap/pen/zxxEdmp

Thought I'd share, as it took me some time to figure out that these mechanisms can be combined to something more than the sum of their parts.
